library(Seurat)
library(leiden)
library(data.table)
## single cell data . The object can be downloaded from CZI https://cellxgene.cziscience.com/collections
load("./KPMP_PREMIERE_SC.Robj")
tcells = subset(kpmp, cells = row.names(kpmp@meta.data)[kpmp$subclass.level.l1 %in% 'Myeloid'])
tdata = tcells[['RNA']]$counts
tcellmeta = tcells@meta.data
sctb = CreateSeuratObject(tdata, min.cells = 3)
sctb = AddMetaData(sctb, metadata = tcellmeta)
sctb$tech = 'single cell'
head(sctb@meta.data)
dim(sctb@meta.data)
library(BPCells)
## single nucleus data. Here the counts and metadata were obtained from local directories. The rawcounts ands meta data can be obtained from https://cellxgene.cziscience.com/collections/
sn.mat <- open_matrix_dir(dir = "./sn/v2_object_filtered-selected/v2_counts_filtered/")
sn = readRDS("./Kidney_Atlas_V2_07-2023_Object_Filtered.Rds")
tb = subset(sn, cells = row.names(sn@meta.data)[sn$v2.subclass.l1 %in% 'Lymphoid'])
tbmeta = tb@meta.data
sn <- CreateSeuratObject(counts = sn.mat)
sntb = subset(sn, cells = row.names(tb@meta.data))
sntb = AddMetaData(sntb, metadata = tbmeta)
sntb$tech = 'single nucleus'
dim(sctb@meta.data)

## integration & annotation . Manual checking on marker list was performed by external researchers 
scsn = merge(sntb, sctb)
scsn[['RNA']]$counts.1 <- convert_matrix_type(scsn[['RNA']]$counts.1, "double")
scsn[['RNA']]$counts.2 <- convert_matrix_type(scsn[['RNA']]$counts.2, "double")
scsn[['RNA']] = JoinLayers(scsn[['RNA']])
scsn[["RNA"]] <- split(scsn[["RNA"]], f = scsn$tech)
scsn <- NormalizeData(scsn)
scsn <- FindVariableFeatures(scsn)
scsn <- ScaleData(scsn)
scsn <- RunPCA(scsn)
scsn <- IntegrateLayers(
object = scsn, method = CCAIntegration,orig.reduction = "pca", new.reduction = "integrated.cca",verbose = TRUE)
scsn <- FindNeighbors(scsn, reduction = "integrated.cca", dims = 1:30)
scsn <- FindClusters(scsn, algorithm = 4,method = 'igraph' , resolution =0.75, cluster.name = "cca.clusters")
scsn <- FindClusters(scsn, algorithm = 4,method = 'igraph' , resolution =1.1, cluster.name = "cca.1.1.clusters")
scsn <- FindClusters(scsn, algorithm = 4,method = 'igraph' , resolution =1.4, cluster.name = "cca.1.4.clusters")
scsn <- RunUMAP(scsn, reduction = "integrated.cca", dims = 1:30, reduction.name = "umap.cca")
DimPlot(scsn, label = T)
Idents(scsn) = "cca.1.0.clusters"
DotPlot(scsn, features = c('IGHD'))
scsn = RenameIdents(scsn,'11' = 'B naive')
DotPlot(scsn, features = c('ANGPTL1'))
scsn = RenameIdents(scsn,'1' = 'B activated')
scsn = RenameIdents(scsn,'14' = 'B memory')
DotPlot(scsn, features = 'ANK3')
scsn = RenameIdents(scsn,  '4' = 'Th-naive')
scsn = RenameIdents(scsn,  '7' = 'Th-naive')
DotPlot(scsn, features = 'JUNB')
scsn = RenameIdents(scsn,  '3' = 'Th-memory')
scsn = RenameIdents(scsn,  '6' = 'Th-memory')
DotPlot(scsn, features = 'CXCR4')
scsn = RenameIdents(scsn,  '19' = 'T CXCR4')
DotPlot(scsn, features = 'SLC4A10')
scsn = RenameIdents(scsn,  '12' = 'MAIT')
DotPlot(scsn, features = 'GZMK')
scsn = RenameIdents(scsn,  '2' = 'CD8+ TEM')
DotPlot(scsn, features = 'ITGA1')
scsn = RenameIdents(scsn,  '9' = 'CD8+ TRM')
scsn = RenameIdents(scsn,  '0' = 'CD8+ T-CYT')
DotPlot(scsn, features = 'HSPA1A')
scsn = RenameIdents(scsn,  '26' = 'CD8+ T-STR')
DotPlot(scsn, features = 'FCGR3A')
scsn = RenameIdents(scsn,  '26' = 'CD8+ TEMRA')
scsn = RenameIdents(scsn,  '5' = 'CD16+ NK')
scsn = RenameIdents(scsn,  '20' = 'CD16- NK')
scsn = RenameIdents(scsn,  '23' = 'ILC3')
scsn = RenameIdents(scsn,  '29' = 'NK_doub')
DotPlot(scsn, features = 'CENPF')
scsn = RenameIdents(scsn,  '28' = 'cycT')
DotPlot(scsn, features = 'MZB1')
scsn = RenameIdents(scsn,  '17' = 'PL')
scsn = RenameIdents(scsn,  '18' = 'PL')
scsn = RenameIdents(scsn,  '21' = 'PL')
DotPlot(scsn, features = 'CUBN')
scsn = RenameIdents(scsn,  '16' = 'T_EPI_doub')
scsn = RenameIdents(scsn,  '25' = 'T_EPI_doub')
DotPlot(scsn, features = 'UMOD')
scsn = RenameIdents(scsn,  '10' = 'T_EPI_doub')
scsn = RenameIdents(scsn,  '15' = 'T_EPI_doub')
scsn = RenameIdents(scsn,  '27' = 'T_EPI_doub')
scsn = RenameIdents(scsn,  '24' = 'T_MYL_doub')
scsn = RenameIdents(scsn,  '13' = 'T_EPI_doub')
scsn1 = subset(scsn, cells = row.names(scsn@meta.data)[!scsn$subclass.level2 %like% 'doub'])
scsn1$subclass.level2 = Idents(scsn1)
save(scsn1, file = "./SCSN_Lymphoid_integrated_052025.Robj")

##code to generate images in Supplementary Figures
pastel_palette <- c("#F6A9A9", "#FFCCB3", "#FFF0B3", "#CDEAC0", "#B3E0E6","#C2B3E6", "#E6B3E0", "#E6B3CC", "#FFB3E0","#FFB3CC","#E6B3FF", "#CCB3FF", "#B3CCFF", "#B3E0FF", "#B3FFF0","#B3FFCC", "#CCFFB3", "#E0FFB3", "#F0FFB3", "#FFCDE6")
DotPlot(scsn2, features = c('ANK3','JUNB','IGHD','BANK1','ANGPTL1','HSPA1A','MKI67', 'GADD45G','SLC4A10','GZMK','ITGA1','CX3CR1','PRF1','RTKN2','CXCR4','PCDH9','XCL1','FCGR3A','MZB1'),   dot.scale = 12, cols = c('lightblue','darkred'))+theme(text = element_text(size=17))+ theme(axis.text.x = element_text(color = "grey20", size = 14, angle = 90, hjust = .5, vjust = .5, face = "plain"))+ theme(axis.title.y  = element_blank(),axis.text.y = element_text(color = "grey20", size = 14,  hjust = .5, vjust = .5, face = "plain"))
DimPlot(scsn2, label = T, group.by = 'v2.subclass.l2', cols = pastel_palette , alpha = 0.5, pt.size = 1.25, label.size = 5, repel = T, split.by = 'tech')+theme(legend.position = 'none')
DimPlot(scsn2, label = F, cols = pastel_palette[c(5,9)] , alpha = 0.5, pt.size = .1, label.size = 5, repel = T, group.by = 'tech')
